ALTER TABLE documents ADD COLUMN IF NOT EXISTS mime TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS size_bytes BIGINT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS blob_url TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS parse_json JSONB;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS preview_html TEXT;
